apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wikijs-db-secret
  namespace: wikijs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: wikijs-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: lab/runtime/wikijs
        property: db_password
